base_url = "https://www.codedmaster.com"
title = "mxaddict"
description = "mxaddict's Blog"
theme = "anemone"
compile_sass = true
build_search_index = true

generate_feeds = true
feed_limit = 10
feed_filenames = ["atom.xml"]

taxonomies = [{ name = "tags" }]

[markdown]
external_links_target_blank = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
author_name = "mxaddict"
author_url = "https://www.codedmaster.com"
list_pages = false

header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/about", name_en = "/about/" },
  { url = "/blog", name_en = "/blog/" }
]

[extra.social]
github = "mxaddict"
gitlab = "mxaddict"
