base_url = "https://www.codedmaster.com"
title = "mxaddict"
description = "mxaddict's Blog"
theme = "zolanight"
compile_sass = true

generate_feeds = true
feed_limit = 10
feed_filenames = ["atom.xml"]

taxonomies = [{ name = "tags" }]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra.zolanight]
theme = "tokyonight"
google_analytics_id = ""
